### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by mase76** [minetest-mods/character_creator#10]
Hi!
I get the following error with the latest git checkout of the mod:

`2017-05-14 14:44:08: ERROR[Main]: ServerError: Lua: Runtime error from mod 'character_creator' in callback on_joinplayer(): /usr/share/games/minetest/mods/character_creator/init.lua:102: attempt to call method 'get_attribute' (a nil value)
2017-05-14 14:44:08: ERROR[Main]: stack traceback:
2017-05-14 14:44:08: ERROR[Main]: 	/usr/share/games/minetest/mods/character_creator/init.lua:102: in function 'load_skin'
2017-05-14 14:44:08: ERROR[Main]: 	/usr/share/games/minetest/mods/character_creator/init.lua:219: in function </usr/share/games/minetest/mods/character_creator/init.lua:218>
2017-05-14 14:44:08: ERROR[Main]: 	/usr/share/games/minetest/builtin/game/register.lua:412: in function </usr/share/games/minetest/builtin/game/register.lua:392>`

**Comment by AntumDeluge** [comment]
I am having the same issue:

> 2017-05-15 18:58:24: ERROR[Main]: ServerError: Lua: Runtime error from mod 'character_creator' in callback on_joinplayer(): ...m-testing/mods/player_visuals/character_creator/init.lua:102: attempt to call method 'get_attribute' (a nil value)
> 2017-05-15 18:58:24: ERROR[Main]: stack traceback:
> 2017-05-15 18:58:24: ERROR[Main]: 	...m-testing/mods/player_visuals/character_creator/init.lua:102: in function 'load_skin'
> 2017-05-15 18:58:24: ERROR[Main]: 	...m-testing/mods/player_visuals/character_creator/init.lua:219: in function <...m-testing/mods/player_visuals/character_creator/init.lua:218>
> 2017-05-15 18:58:24: ERROR[Main]: 	/usr/share/minetest/builtin/game/register.lua:412: in function </usr/share/minetest/builtin/game/register.lua:392>

Using Minetest server 0.4.15 with `character_creator` build 6a0e6aa:
```
$ minetest --version
Minetest 0.4.15 (Linux)
Using Irrlicht 1.8.3
Build info: VER=0.4.15 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
```

**Comment by ghost** [comment]
https://github.com/minetest-mods/character_creator/releases
You can download 0.9 here. It supports 0.4.15 ;)

**Comment by AntumDeluge** [comment]
Newest Git dev build should work with 0.4.16 release?

**Comment by ghost** [comment]
Yes.

**Comment by AntumDeluge** [comment]
Yay! It's working. Thank you @Rui-Minetest. :smile:
