### ISSUE TITLE
not compatible with latest 3d_armor master

### ISSUE THREAD

**Issue by verymilan** [minetest-mods/character_creator#6]
Hi, i just got an `ServerError: Runtime error from mod 'character_creator' in callback environment_Step(): ...in/../games/minetest_game/mods/3d_armor/3d_armor/api.lua:158: bad argument #1 to 'gsub' (string expected, got nil)` error - seems like 3d_armor got a breaking change for character_creator.

**Comment by ghost** [comment]
#5
2131db4
