### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/character_creator#7]
Hi,

could you please tag releases so I can make packages for Debian?

Thanks!

Snark on #minetest

**Comment by ghost** [comment]
Sorry, I can't. The mod has a critical bug.
Please wait until I fix it...

My PC is broken, so fixing may be much later...

**Comment by SnarkBoojum** [comment]
Eh, avoiding to package random commits which might have critical bugs is precisely why I'm asking for tagged releases, so you're welcome!

**Comment by ghost** [comment]
#8 
This will be 1.0.
Please wait until it is merged...

**Comment by SnarkBoojum** [comment]
I'll wait until you tag and close this report :-)

(and after that, I'll get notified anytime you tag a new release)

**Comment by ghost** [comment]
https://github.com/minetest-mods/character_creator/releases

Sorry, 1.0 seems to require 0.4.15-dev or above...
Could you make 0.9 package for now?
