### ISSUE TITLE
Wrong fork relationships...

### ISSUE THREAD

**Issue by ghost** [minetest-mods/character_creator#9]
@pinkysnowman
Would you delete your character_creator repo if you aren't using it?
I deleted my one, yours became this repo's parent now...🤔

@sofar 
Could you detach fork relationships?

**Comment by sofar** [comment]
github support ticket requested. I will update this when I hear back.

**Comment by sofar** [comment]
detached by github support.

**Comment by ghost** [comment]
Thank you.
